services:
  frontend:
    build: .
    container_name: PROJECT_NAME-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - internal

networks:
  internal:
    driver: bridge
